import './globals.css';

import { dehydrate } from '@tanstack/react-query';
import type { Metadata } from 'next';
import { cookies } from 'next/headers';

import { iranSans } from '@/components/font';
import { makeQueryClient } from '@/lib/query-client';
import { extractUser } from '@/lib/roles';
import { cn } from '@/lib/utils';
import AuthProvider from '@/providers/auth.provider';
import { authKeys } from '@/services/features/auth/hooks';
import { getMe } from '@/services/features/auth/server.api';
import { UserResponse } from '@/services/features/auth/types';

import Providers from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/** Only authoritative API data is hydrated; never fall back to request headers. */
async function resolveUser(): Promise<UserResponse | null> {
  const cookieStore = await cookies();
  if (!cookieStore.has('access_token')) return null;
  try {
    return extractUser(await getMe());
  } catch {
    return null;
  }
}

/**
 * کاربر را از سرور می‌گیریم و در کش react-query می‌گذاریم تا
 * در اولین رندر مرورگر هم در دسترس باشد (بدون پرش/خالی ماندن منوها).
 */
function buildDehydratedState(user: UserResponse | null) {
  const queryClient = makeQueryClient();

  if (user) {
    queryClient.setQueryData(authKeys.me, {
      status: 200,
      message: '',
      data: user,
    });
  }

  return dehydrate(queryClient);
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await resolveUser();

  return (
    <html
      lang="fa"
      dir="rtl"
      className={cn('h-full', 'antialiased', 'font-sans', iranSans.className)}
    >
      <body className="min-h-full flex flex-col">
        <Providers dehydratedState={buildDehydratedState(user)}>
          <AuthProvider>{children}</AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
