import './globals.css';

import type { Metadata } from 'next';
import { headers } from 'next/headers';

import { iranSans } from '@/components/font';
import { cn } from '@/lib/utils';
import AuthProvider from '@/providers/auth.provider';
import { UserResponse } from '@/services/features/auth/types';
import { getMe } from '@/services/features/auth/server.api';

import Providers from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * تلاش می‌کنه کاربر رو از API بگیره.
 * اگه API خطا داد (مثلاً توکن منقضی)، از header middleware استفاده می‌کنه.
 */
async function resolveUser(): Promise<UserResponse | null> {
  // ۱. تلاش برای گرفتن کاربر از API
  try {
    const response = await getMe();
    if (response?.data) {
      return response.data;
    }
  } catch (error) {
    // getMe خطا داد — از middleware header استفاده کن
  }

  // ۲. fallback: خواندن اطلاعات کاربر از header middleware
  try {
    const headerStore = await headers();
    const userPayload = headerStore.get('X-User-Payload');
    if (userPayload) {
      const parsed = JSON.parse(userPayload);
      return {
        id: parsed.id,
        fullName: parsed.fullName,
        roles: parsed.roles,
        birthDate: parsed.birthDate,
        phone: parsed.phone,
        isActive: parsed.isActive,
      } as UserResponse;
    }
  } catch {
    // header وجود نداره یا parse نشد
  }

  return null;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await resolveUser();

  return (
    <html
      lang="fa"
      dir="rtl"
      className={cn('h-full', 'antialiased', 'font-sans', iranSans.className)}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <AuthProvider initialUser={user}>{children}</AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
